### ISSUE TITLE
Exception call is using namespace

### ISSUE THREAD

**Issue by itsmill3rtime** [mrteye/GDAX#3]
In your code you have `throw new Exception` which itself causes an error, need to change to `throw new \Exception` (add the slash) on all the places you use it. otherwise it is looking for an Exception class within the `mrteye\Gdax` namespace

**Comment by BenMoreton** [comment]
The same:

> Fatal error: Uncaught Error: Class 'mrteye\Gdax\Exception' not found in /var/app/current/vendor/mrteye/gdax/src/Api.php:99
Stack trace:
#0 /var/app/current/vendor/mrteye/gdax/src/Api.php(63): mrteye\Gdax\Api->_call('GET', 'accounts', '', Array)
#1 /var/app/current/vendor/mrteye/gdax/src/Api.php(120): mrteye\Gdax\Api->_privateRequest('GET', 'accounts')

**Comment by mrteye** [comment]
Thanks.  I updated the exception namespaces.  They are now all preceded by a forward slash.

I also added some working examples in the test folder and shortened the timeout for curl...so we can see those exceptions in seconds rather than minutes.
