### ISSUE TITLE
Problem using Examples

### ISSUE THREAD

**Issue by jmashore** [mrteye/GDAX#4]
[testGDAX.zip](https://github.com/mrteye/GDAX/files/1597653/testGDAX.zip)
I have installed using composer as per instructions. 
Then copy and pasted example #1 
The very first thing I get is Exception about the GDX\Exception not found. I've attached my code. I'm sure "m just missing something obvious. Thank you for your help

C:\ProjectFiles\btcgdax\public>php testGDAX.php
PHP Fatal error:  Uncaught Error: Class 'mrteye\Gdax\Exception' not found in C:\ProjectFiles\btcgdax\vendor\mrteye\gdax\src\Api.php:99
Stack trace:
#0 C:\ProjectFiles\btcgdax\vendor\mrteye\gdax\src\Api.php(58): mrteye\Gdax\Api->_call('GET', 'products', '')
#1 C:\ProjectFiles\btcgdax\vendor\mrteye\gdax\src\Api.php(656): mrteye\Gdax\Api->_publicRequest('GET', 'products')
#2 C:\ProjectFiles\btcgdax\public\testGDAX.php(20): mrteye\Gdax\Api->getProducts()
#3 {main}
  thrown in C:\ProjectFiles\btcgdax\vendor\mrteye\gdax\src\Api.php on line 99

Fatal error: Uncaught Error: Class 'mrteye\Gdax\Exception' not found in C:\ProjectFiles\btcgdax\vendor\mrteye\gdax\src\Api.php:99
Stack trace:
#0 C:\ProjectFiles\btcgdax\vendor\mrteye\gdax\src\Api.php(58): mrteye\Gdax\Api->_call('GET', 'products', '')
#1 C:\ProjectFiles\btcgdax\vendor\mrteye\gdax\src\Api.php(656): mrteye\Gdax\Api->_publicRequest('GET', 'products')
#2 C:\ProjectFiles\btcgdax\public\testGDAX.php(20): mrteye\Gdax\Api->getProducts()
#3 {main}
  thrown in C:\ProjectFiles\btcgdax\vendor\mrteye\gdax\src\Api.php on line 99

**Comment by jmashore** [comment]
I believe I have resolved this issue. It appears the composer version is not the current version on github. I had to manually add/copy over with the new classes and modify associated autoloads with the correct information. Example #1 now runs as expected.

**Comment by mrteye** [comment]
Good Find.  Packagist was pointed at the Gitlab repository.  I have directed it toward Github and added a post commit hook to efficiently capture future updates.

Additionally, I have updated the examples in the test folder.  They should be a little easier to setup and use.

Thank you for your feedback.
